####################################################
# OUR DISCORD CHANNEL: https://discord.aslstd.org/ #
####################################################

health-bar:
  fix-to-one-line: false
  health-per-bar: 20

enable-console-colors: true
debug:
  enable-debug: false
  less-console-messages: false
  console-feedback: true

# Time in seconds (default 8 hours)
check-period: 28800
check-updates: true

modules:
  player-attributes-enabled: false