name: Build & Deploy

on:
    push:
      branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        server-id: grandwork
        server-username: GW_USERNAME
        server-password: GW_PASSWORD

    - name: Build & Publish
      run: mvn --batch-mode install --file pom.xml
      env:
        GW_USERNAME: ${{ secrets.SRV_USERNAME }}
        GW_PASSWORD: ${{ secrets.SRV_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        
    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mc-open-lib
        path: test-server/plugins/*.jar

